version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  ir-receiver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    network_mode: "host"
    depends_on:
      - redis
  neochi-app:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/code
    network_mode: "host"
    depends_on:
      - redis
      - ir-receiver
